# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-02 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=264, unique=True)),
                ('Email', models.CharField(max_length=264, unique=True)),
                ('salary', models.CharField(max_length=264)),
            ],
        ),
    ]
